name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://allenblog.zeabur.app/rss.xml"
          max_post_count: 6
          disable_item_validation: true
          item_exec: "if (!post.title) post = null;" #to skip post that dont have title
          date_format: yy-mm-dd
