name: Contribution Snake

on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 使用 v3 作為最新的穩定版本

      - name: Generate Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/contribution-snake.svg
            assets/contribution-snake-dark.svg?palette=github-dark

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Pull latest changes
        run: git pull origin master

      - name: Commit and Push changes
        run: |
          git add assets/contribution-snake.svg assets/contribution-snake-dark.svg
          git commit -m "chore: generate contribution snake"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
