name: Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Use v3 as the latest stable version

      - name: Generate Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/contribution-snake.svg
            assets/contribution-snake-dark.svg?palette=github-dark
           
      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/contribution-snake.svg, assets/contribution-snake-dark.svg"
          message: "chore: generate contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
